= Querying with {sqlpp}
:description: You can query for documents in Couchbase using the {sqlpp} query language, a language based on SQL, but designed for structured and flexible JSON documents.
// :page-aliases: n1ql-query.adoc,n1ql-queries-with-sdk.adoc
// :page-aliases: ROOT:document-operations.adoc,ROOT:documents-creating,ROOT:documents-updating,ROOT:documents-retrieving,ROOT:documents-deleting,n1ql-queries-with-sdk.adoc


[abstract]
{description}



On this page we dive straight into using the Query Service API from the {name-sdk}.
For a deeper look at the concepts, to help you better understand the Query Service, and the {sqlpp} language, see the links in the <<further-information,Further Information>> section at the end of this page.




Here we show queries against the Travel Sample collection, at cluster and scope level,
and give links to information on adding other collections to your data.
// kafka
// postgres
// capella


== Before You Start

This page assumes that you have xref:hello-world:start-using-sdk.adoc[installed the {name-sdk}], added your IP address to the allowlist, and xref:columnar:admin:prepare-project.adoc#cluster[created a Columnar cluster].

Create a collection to work upon by xref:columnar:intro:examples.adoc#travel-sample[importing the travel-sample dataset] into your cluster.



== Querying Your Dataset


The Go SDK will always return streaming response from the server.

Execute a query:

.Scope Level
[source,go]
----
include::devguide:example$queries.go[tags=scopeLevelQuery]
----


.Cluster Level
[source,go]
----
include::devguide:example$queries.go[tags=clusterLevelQuery]
----


=== Positional and Named Parameters

Supplying parameters as individual arguments to the query allows the query engine to optimize the parsing and planning of the query. You can either supply these parameters by name or by position.

Execute a streaming query with positional arguments:

.Positional Parameters
[source,go]
----
include::devguide:example$queries.go[tags=positionalParamQuery]
----

Execute a streaming query with named arguments:

.Named Parameters
[source,go]
----
include::devguide:example$queries.go[tags=namedParamQuery]
----

== Query Options
The query service provides an array of options to customize your query. The following table lists them all:

.Available Query Options
[options="header"]
|====
| Name       | Description
| `NamedParameters map[string]interface{}` | Allows to set named arguments for a parameterized query.
| `PositionalParameters []interface{}` | Allows to set positional arguments for a parameterized query.
| `Priority bool` | Allows to set whether this query should be assigned as high priority by the analytics engine.
| `Raw interface{}` | Escape hatch to add arguments that are not covered by these options.
| `ReadOnly bool` | Tells the client and server that this query is readonly.
| `ScanConsistency QueryScanConsistency` | Sets a different scan consistency for this query.
| `Unmarshaler Unmarshaler` | Sets a different `Unmarshaler` for this query.
|====

== Handling Results

When performing a query, the response you receive is a `QueryResult`.
If no error occurs the request succeeded and provides access to both the rows returned and also associated `QueryMetadata`.

Rows are returned through the `NextRow()` function on the result.
This function returns a `QueryResultRow` providing access to your data.
The data is read using the `ContentAs` function by supplying a pointer to the variable in which to store the value.
Always remember to check the error value of `Err` after iterating the results, this is where any errors occurring whilst calling `NextRow` will be returned.

[source,go]
----
include::devguide:example$queries.go[tags=handleResults]
----

Closing a result stream early can be done by calling the `context.CancelFunc` associated with the `context.Context` provided to `ExecuteQuery`.

=== Buffered results

The Go SDK provides a utility function to enable you to buffer all of the results of a query into memory.
When using this function there is no need to check the value of `Err` after iterating the results as the function will return an error if one occurs.

[source,go]
----
include::devguide:example$queries.go[tags=bufferResults]
----

=== Metadata

The `QueryMetadata` provides insight into some basic profiling/timing information as well as information like any warnings generated whilst executing the query.
Metadata can only be accessed once all rows have been read from the result, early access will result in an error being returned.

.Query MetaData fields
[options="header"]
|====
| Name       | Description
| `Metrics QueryMetrics` | Metrics generated by the query engine for the request.
| `RequestID string` | The request identifier of this request.
| `Warnings []QueryWarning` | Non-fatal errors that occurred during query execution.
|====

[source,go]
----
include::devguide:example$queries.go[tags=metadata]
----

== Further Information

The xref:server:analytics:1_intro.adoc[{sqlpp} for Analytics Reference]
offers a complete guide to the SQL++ language for both of our analytics services, including all of the latest additions.



