= Full Installation
:description: Installation instructions for the Couchbase Go Client.
:page-toclevels: 2
:page-partial:

[abstract]
{description}

Columnar SDKs are developed from the ground-up and while they maintain some syntactic similarities with the xref:home:ROOT:sdk.adoc[operational SDKs],
they are purpose built for Columnar's analytical use cases.
They support streaming APIs to handle large datasets, as well as the common features expected to be present in any modern database SDK --
such as connection management and robust error handling.




== Installing the SDK

The Go Columnar SDK has added support for https://github.com/golang/go/wiki/Modules[Go Modules]. 
You can use `go get` to download the SDK:

IMPORTANT: `go get` only works if you have initialised a https://go.dev/blog/using-go-modules[Go module], and have a `go.mod` file in your working directory.

[source,console]
----
$ go get github.com/couchbase/go-columnar@v1.0.0
----

NOTE: In line with the https://golang.org/doc/devel/release.html#policy[Golang project], Couchbase supports both the current, and the previous, versions of Go.
Earlier versions may work, but are not supported.

Information about new features, fixes, and known issues -- as well as information about how to install earlier release versions -- is in the xref:columnar-sdk-release-notes.adoc[release notes].


